#!/bin/bash
    ../simulador/simulador -level 3124 -defenses 30 -defensetypes 30 -defenserandomness 0.5  -pases 0.5 -time 1500
    ../simulador/simulador -level 3125 -defenses 40 -defensetypes 40 -defenserandomness 0.6  -pases 0.6 -time 1500
    ../simulador/simulador -level 3054 -defenses 40 -defensetypes 30 -defenserandomness 0.4  -pases 0.4 -time 1500
    ../simulador/simulador -level 3056 -defenses 50 -defensetypes 40 -defenserandomness 0.5  -pases 0.5 -time 1500
    ../simulador/simulador -level 3056 -defenses 40 -defensetypes 20 -defenserandomness 0.7  -pases 0.7 -time 1500
    ../simulador/simulador -level 3056 -defenses 50 -defensetypes 50 -defenserandomness 0.5  -pases 1 -time 1500
    ../simulador/simulador -level 3052 -defenses 40 -defensetypes 40 -defenserandomness 0.5  -pases 0.5 -time 1500
    ../simulador/simulador -level 3028 -defenses 60 -defensetypes 50 -defenserandomness 0.6  -pases 0.6 -time 1500
    ../simulador/simulador -level 4056 -defenses 70 -defensetypes 70 -defenserandomness 0.3  -pases 0.3 -time 1500
    ../simulador/simulador -level 4092 -defenses 80 -defensetypes 70 -defenserandomness 0.5  -pases 0.5 -time 1500

    rm file.txt
    ../simulador/simulador -level 3124 -defenses 30 -defensetypes 30 -defenserandomness 0.5  -pases 0.5 -time 1500 >> file.txt
    ../simulador/simulador -level 3125 -defenses 40 -defensetypes 40 -defenserandomness 0.6  -pases 0.6 -time 1500 >> file.txt
    ../simulador/simulador -level 3054 -defenses 40 -defensetypes 30 -defenserandomness 0.4  -pases 0.4 -time 1500 >> file.txt
    ../simulador/simulador -level 3056 -defenses 50 -defensetypes 40 -defenserandomness 0.5  -pases 0.5 -time 1500 >> file.txt
    ../simulador/simulador -level 3056 -defenses 40 -defensetypes 20 -defenserandomness 0.7  -pases 0.7 -time 1500 >> file.txt
    ../simulador/simulador -level 3056 -defenses 50 -defensetypes 50 -defenserandomness 0.5  -pases 1 -time 1500 >> file.txt
    ../simulador/simulador -level 3052 -defenses 40 -defensetypes 40 -defenserandomness 0.5  -pases 0.5 -time 1500 >> file.txt
    ../simulador/simulador -level 3028 -defenses 60 -defensetypes 50 -defenserandomness 0.6  -pases 0.6 -time 1500 >> file.txt
    ../simulador/simulador -level 4056 -defenses 70 -defensetypes 70 -defenserandomness 0.3  -pases 0.3 -time 1500 >> file.txt
    ../simulador/simulador -level 4092 -defenses 80 -defensetypes 70 -defenserandomness 0.5  -pases 0.5 -time 1500 >> file.txt

